apiVersion: v1
kind: Service
metadata:
  name: dipti-kubernetes-final-service
spec:
  type: NodePort
  selector:
    app: dipti-kubernetes-final
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30007
